"""add notes to expenses

Revision ID: d0de380f4e3b
Revises: 2bfc5e5d1c87
Create Date: 2026-08-22 17:20:49.470044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0de380f4e3b'
down_revision: Union[str, Sequence[str], None] = '2bfc5e5d1c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'notes')
    # ### end Alembic commands ###
